export const SET_USER = "SET_USER";
export const SET_STATUS_LOGIN = "SET_STATUS_LOGIN";

// tool
export const SET_STATUS_SLIDE_BAR = "SET_STATUS_SLIDE_BAR";
export const SET_STATUS_DIALOG = "SET_STATUS_DIALOG";
export const SET_STATUS_DIALOG_UPLOAD_OPTION_IMAGE =
    "SET_STATUS_DIALOG_UPLOAD_OPTION_IMAGE";
export const CHANGE_STATUS_PROPGRESS = "CHANGE_STATUS_PROPGRESS";

// sign out
export const CLEAN_ALL_SURVEY_REDUCER = "CLEAN_ALL_SURVEY_REDUCER";
export const CLEAN_SURVER_REDUCER = "CLEAN_SURVER_REDUCER";

// home page
export const SET_SURVER_IN_HOME_PAGE = "SET_SURVER_IN_HOME_PAGE";
export const SORT = "SORT";
export const SEARCH = "SEARCH";
export const SET_VIEW_MODE = "SET_VIEW_MODE";

// create new survey
export const SET_SURVEY = "SET_SURVEY";
export const SET_TITLE_FORM = "SET_TITLE_FORM";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const CHANGE_TYPE_QUESTION = "CHANGE_TYPE_QUESTION";
export const CHANGE_TITLE_QUESTION = "CHANGE_TITLE_QUESTION";
export const CHANGE_OPTION = "CHANGE_OPTION";
export const SET_OPTION = "SET_OPTION";
export const CHANGE_REQUIRED = "CHANGE_REQUIRED";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const CHANGE_STATUS_OPEN_QUESTION = "CHANGE_STATUS_OPEN_QUESTION";
export const SET_INTERFACE_COLOR = "SET_INTERFACE_COLOR";
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_QUESTION_IMAGE = "SET_QUESTION_IMAGE";
export const SET_OPTION_IMAGE = "SET_OPTION_IMAGE";
export const CREATE_SUBMIT_FORM = "CREATE_SUBMIT_FORM";
export const PUSH_VALUE_TO_SUBMIT_REDUCER = "PUSH_VALUE_TO_SUBMIT_REDUCER";
